name: kalm
version: 0.0.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - HaskellNet
    - HaskellNet-SSL
    - attoparsec
    - bytestring
    - case-insensitive
    - envparse
    - lens
    - monad-logger
    - mtl
    - network
    - optparse-applicative
    - path
    - path-io
    - persistent
    - persistent-sqlite
    - persistent-template
    - purebred-email
    - text
    - unliftio
    - validity
    - validity-bytestring
    - validity-text
    - yaml
    - yamlparse-applicative

executables:
  kalm:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kalm

tests:
  kalm-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellNet
    - HaskellNet-SSL
    - QuickCheck
    - bytestring
    - case-insensitive
    - genvalidity
    - genvalidity-bytestring
    - genvalidity-sydtest
    - genvalidity-text
    - kalm
    - monad-logger
    - network
    - path
    - path-io
    - persistent
    - port-utils
    - process
    - purebred-email
    - sydtest
    - sydtest-persistent
    - sydtest-persistent-sqlite
    - sydtest-process
    - sydtest-typed-process
    - text
    - typed-process
